baseURL = "https://blogs.akshat-sharma.tech"
languageCode = "en-us"
Title = "Akshat's Blog"
theme="archie"
copyright = "© Akshat Sharma"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = 'G-EXZTPQWE8N'

[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5

[params]
	mode="dark"
	useCDN=true
	subtitle = "A place where I write about my journey through the tech industry!"
	description = "A place where I write about my journey through the tech industry!"
	favicon = "https://i.imgur.com/yn0lf5g.png"
	og_image = "https://i.imgur.com/yn0lf5g.png"
	dateFormat = "2 January, 2006"


[[params.social]]
	name = "GitHub"
	icon = "github"
	url = "https://github.com/akshat2602"

[[params.social]]
	name = "Twitter"
	icon = "twitter"
	url = "https://twitter.com/akshat2602"

[[params.social]]
	name = "Linkedin"
	icon = "linkedin"
	url = "https://www.linkedin.com/in/akshat-sharma-2602/"


[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "all posts"
url = "/posts"
weight = 2


[[menu.main]]
name = "tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "about"
url = "https://akshat-sharma.tech"
weight = 4
