baseURL: "https://akshatsharma.xyz"
title: Akshat Sharma
titlepage: Home
paginate: 4
theme: hugo-winston-theme

params:
    addDot: true
    addFrame: true
    highlightColor: '#6272A4'
    baseColor: '#282a36'
    baseOffsetColor: '#44475a'
    headingColor: '#f8f8f2'
    textColor: '#f8f8f2'
    dotColor: '#6272A4'
    showAuthorOnHomepage: true
    showAuthorOnPosts: false
    showIntroContentOnHomepage: true


minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: posts
                  url: /posts
                  weight: 1
                # - name: about
                  # url: /about
                  # weight: 2
                - name: tags
                  url: /tags
                  weight: 4
                - name: "resume"
                  url: "https://resume.akshatsharma.xyz/"
                  params:
                      external: true

outputs:
    home:
        - HTML
        - RSS

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        style: dracula
        lineNos: false
        noClasses: false

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
