baseURL: "https://akshatsharma.xyz"
title: Akshat Sharma
paginate: 5
theme: PaperModX

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "hi 👋, my name is Akshat Sharma"
    author:
        - Akshat
    mainSections:
        - home
        - posts
        - notes
    disableAnchoredHeadings: true
    images: ["index.png"]
    DateFormat: "2 January, 2006"
    useCustomAnalytics: false
    favicon: "https://i.imgur.com/yn0lf5g.png"
    apple-touch-icon: "https://i.imgur.com/yn0lf5g.png"

    defaultTheme: "dark"
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    ShowWordCount: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    TocOpen: true
    TocSide: "left"
    EnableInstantClick: true
    EnableImageZoom: true

    # For a commenting system, not really needed right now
    commentSystems:
        # disqus:
        #     shortname: reorx
        # remark42:
        #     url: https://remark42.reorx.com
        #     site: reorx.github.io
        # telegramWidget:
        #     channel: reorx_share
        #     accentColor: "9077e1"
        #     limit: 20
        giscus: 
          shortname: akshat2602
    defaultCommentSystems:
        giscus: true

    profileMode:
        enabled: false
        title: "hi 👋, my name is Akshat Sharma"
        subtitle: "student/engineer, always trying to learn things"
        imageUrl: "akshat.png"
        imageTitle: Akshat Sharma
        imageWidth: 350
        imageHeight: 350
        buttons:
            - name: posts
              url: /posts/
            - name: resume
              url: "https://resume.akshatsharma.xyz/"

    homeInfoParams:
        Title: _a student and an engineer_
        Content: |
            hi 👋, my name is Akshat Sharma, I'm currently a CS grad student working in the [File Systems and Storage Lab(FSL)](https://www.fsl.cs.stonybrook.edu/) at Stony Brook University. 

            I'm currently researching secure archival storage systems and their applications. I'm interested in learning about databases, operation systems, distributed systems and have worked in distributed systems at [Stony Systems Lab](http://mpaxos.com) before working in FSL. 

            Here, I post things that I find interesting/notes that I want to share with the world.
    socialIcons:
        - name: github
          url: "https://github.com/akshat2602"
        - name: linkedin
          url: "https://linkedin.com/in/akshat-sharma-2602/"
        - name: goodreads
          url: "https://www.goodreads.com/user/show/54753277-akshat"
        - name: letterboxd
          url: "https://letterboxd.com/akshat2602/"
        - name: "Cal.com"
          url: "https://cal.com/akshat2602"
        - name: peerlist
          url: "https://peerlist.io/akshat2602"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/16431252/akshat-sharma"
        - name: email
          url: "mailto: mail@akshatsharma.xyz"
        - name: rss
          url: "index.xml"

    editPost:
        URL: "https://github.com/akshat2602/personal-website/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: About Me
                  url: /about/
                  weight: 1
                - name: posts
                  url: /posts
                  weight: 4
                # - name: newsletter
                #   url: /newsletter/
                #   weight: 1
                # - name: notes
                #   url: /notes
                #   weight: 4
                - name: tags
                  url: /tags
                  weight: 4
                - name: archives
                  url: /archives/
                  weight: 5
                - name: search
                  url: /search/
                  weight: 10
                - name: "resume"
                  url: "https://resume.akshatsharma.xyz/"
                  params:
                      external: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        style: dracula
        lineNos: false
        noClasses: false

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
